on:
  pull_request:
    types: [labeled, edited]

jobs:
  pdf-bibliography:
    name: A job to check bibliography in pdf files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get paths
      run: |
        git diff-tree --no-commit-id --name-status -r ${{ github.sha }} > CHANGED_FILES_PATHS.txt
    - uses: amarhod/pdf-bibliography-action@pdf-parse
      with:
        token: ${{ github.token }}
        repo_path: ./
        repo_name: ${{ github.repository }}
        pr_number: ${{ github.event.number }}